### ISSUE TITLE
Crash when a Immersive Railroading train produces a... sound?

### ISSUE THREAD

**Issue by 1gn4ac10** [kappa-maintainer/Sound-Physics#4]
By the description, this mod supposedly supports Immersive Railroading, but when I try to use both, it looks like if a train produces a sound, the game will crash. Not sure what more to explain

[crash-2024-06-04_15.52.49-client.txt](https://github.com/user-attachments/files/15569738/crash-2024-06-04_15.52.49-client.txt)

**Comment by kappa-maintainer** [comment]
IR got some new versions recently, I will check about it

**Comment by kappa-maintainer** [comment]
[Sound-Physics-1.12.2-1.zip](https://github.com/user-attachments/files/15885149/Sound-Physics-1.12.2-1.zip)
Try this build

**Comment by 1gn4ac10** [comment]
Yep, now it looks like it's working!
