### ISSUE TITLE
Some sounds have too much range 

### ISSUE THREAD

**Issue by Margatroidu** [kappa-maintainer/Sound-Physics#5]
Some sounds can be heard a hundred blocks away as if he were right next to you. For example, this happens with dispenser.
Watch video:

https://github.com/kappa-maintainer/Sound-Physics/assets/165489993/c39f12cf-5dbb-4364-9164-05bd2be3b3bb

And the same thing happens with a pressure plate.

**Comment by kappa-maintainer** [comment]
There must be a scale problem, like somehow made it ten times long
Which version were involved? Does it happen in all versions?

**Comment by Margatroidu** [comment]
> There must be a scale problem, like somehow made it ten times long Which version were involved? Does it happen in all versions?

Yes, this happens in all versions and I'm currently using the most recent one

**Comment by kappa-maintainer** [comment]
After some investigation, I found that's identical with the original mod
Please try to set distance manually in config and see if other sound works correctly

**Comment by Margatroidu** [comment]
> After some investigation, I found that's identical with the original mod Please try to set distance manually in config and see if other sound works correctly

I've changed the distance to a value of 1.0 and the sound now has a distance of 50 blocks, which is also a lot and the sound is still heard as if you were standing next to it
That didn't solve the problem

**Comment by kappa-maintainer** [comment]
You are right, other sounds do have a reasonable distance
So dispenser sound must be played different, I will check about it

**Comment by Margatroidu** [comment]
> So dispenser sound must be played different, I will check about it

Check the same with a pressure plate, the sound from it has the same problem as a dispenser

**Comment by kappa-maintainer** [comment]
Try this
[soundphysics-1.zip](https://github.com/user-attachments/files/18047929/soundphysics-1.zip)

**Comment by Margatroidu** [comment]
It's all the same
Plus now the sounds on the surface sound like they're coming from underwater. This is especially noticeable when breaking grass. Watch the video.

https://github.com/user-attachments/assets/1cf6c38d-b5c7-439b-962f-0c371b946823

**Comment by kappa-maintainer** [comment]
I think I found the reason
`NOTE: In OpenAL, rolloff attenuation only works for monotone sounds.`
I guess using linear attenuation is the only option here...

**Comment by Margatroidu** [comment]
Hi, any news?

**Comment by kappa-maintainer** [comment]
Switching to linear attenuation muted all in-game sounds, haven't figure out why

**Comment by Margatroidu** [comment]
I think I know how to solve this issue
This issue with the range of sounds only exists for one sound, the vanilla click sound `click.ogg`
Sound Physics is most likely doing something to the operation of this sound. I think the past developer wanted to fix a problem where in the menu click sounds sometimes sounded to different ears. On 1.12.2, depending on how you turn your gaze, the click sound sounds different depending on how you look at it (if it's not clear, watch the video. I didn't use any mods there). But it's only noticeable when you use resource packs with other sounds
Sound Physics changes all sounds and apparently it affected click sounds and because of this bug the sound is missing (similar to this bug - https://github.com/kappa-maintainer/Sound-Physics/issues/11). And then the original developer made that sound on stereo, but it makes the click sound range become abnormal
Try looking in the code to see what the mod will do with click sound. And, if you can, try isolating the operation of this mod to this sound

https://github.com/user-attachments/assets/e485325d-7eab-4848-913e-74ca2fb5ffe2

**Comment by kappa-maintainer** [comment]
There's no special handle to any sound, but now I realize what could be the problem

**Comment by kappa-maintainer** [comment]
ffprobe shows that the clicks sound is stereo while most other sounds are mono

**Comment by kappa-maintainer** [comment]
I think I figured out, the click sound was used both in world and out world, but the GUI Sound filter failed to find their difference
Will release 1.1.7 soon

**Comment by kappa-maintainer** [comment]
[soundphysics-1.zip](https://github.com/user-attachments/files/18269506/soundphysics-1.zip)
Try this build

**Comment by Margatroidu** [comment]
> Try this build [soundphysics-1 (1).zip](https://github.com/user-attachments/files/18269636/soundphysics-1.1.zip)

That's great! Click sound now. The click sound is now very quiet over long distances. I think it's a win.

**Comment by Margatroidu** [comment]
But now I've noticed that the sounds are creating fps spikes. But I think that's a different problem altogether

**Comment by Margatroidu** [comment]
> > Try this build [soundphysics-1 (1).zip](https://github.com/user-attachments/files/18269636/soundphysics-1.1.zip)
> 
> That's great! The click sound is now very quiet over long distances. I think it's a win.

I think it would be better to make the sound even quieter from a distance, if possible

**Comment by kappa-maintainer** [comment]
It shares same global factor with all other sounds

**Comment by Margatroidu** [comment]
All right, then. That's a lot better than it was originally

**Comment by Margatroidu** [comment]
> But now I've noticed that the sounds are creating fps spikes. But I think that's a different problem altogether

can you fix the fps spikes problem? I just put the mod on my modpack and my fps dropped significantly

**Comment by kappa-maintainer** [comment]
Make two spark profiling before and after adding the mod

**Comment by Margatroidu** [comment]
Here, but I still want to do it on my modpack

Without mod - https://spark.lucko.me/dtfLsGApZl

With mod - https://spark.lucko.me/sF1607fDoe

**Comment by Margatroidu** [comment]
> Here, but I still want to do it on my modpack
> 
> Without mod - https://spark.lucko.me/dtfLsGApZl
> 
> With mod - https://spark.lucko.me/sF1607fDoe

I noticed that these fps skipes are in vanilla without mods

**Comment by Margatroidu** [comment]
No, I was wrong, sound physics has nothing to do with it. it doesn't affect fps.

**Comment by Margatroidu** [comment]
I think this problem has already been solved. Should I close this bug report?
