### ISSUE TITLE
Strange echo 

### ISSUE THREAD

**Issue by Margatroidu** [kappa-maintainer/Sound-Physics#6]
I found a new problem: there is a strange echo from different sound sources from different mods. I specifically noticed this with Dynamic Surroundings and Actually Additions mods

With Sound Physics:

https://github.com/kappa-maintainer/Sound-Physics/assets/165489993/4fe554c9-372c-43da-924d-63967b978823

Without Sound Physics:

https://github.com/kappa-maintainer/Sound-Physics/assets/165489993/00513cc4-5365-40b5-a370-90fd6c35ffb8

**Comment by kappa-maintainer** [comment]
The reverb trigger logic may be broken in such case, will check about that

**Comment by Margatroidu** [comment]
Any updates?

**Comment by kappa-maintainer** [comment]
Busying with irl problem, please wait patiently

**Comment by kappa-maintainer** [comment]
Busying with Cleanroom recently, may take a look before 2025

**Comment by Margatroidu** [comment]
Hi! I'd like to see an update. I've been waiting a long time

**Comment by kappa-maintainer** [comment]
I made some tests in similar situation but can't reproduce the extra reverb, how did it happen? Did it only happen in that save or any normal overworld surface? Have you installed other mods?

**Comment by kappa-maintainer** [comment]
I just found the original mod added patches to DS in 1.7.10, looking at it

**Comment by kappa-maintainer** [comment]
DS has a weird sound delay mechanic, checking that

**Comment by Margatroidu** [comment]
> I made some tests in similar situation but can't reproduce the extra reverb, how did it happen? Did it only happen in that save or any normal overworld surface?

This happened on all saves. For this test I just created a new modpack and added those two mods.

**Comment by Margatroidu** [comment]
I just installed this mod only with Actually Additions and the problem is still the same

**Comment by kappa-maintainer** [comment]
Sorry for taking such a long time... It was a dumb mistake in the first batch of changes

**Comment by Margatroidu** [comment]
Thank you!
