### ISSUE TITLE
Post releases of this fork so people can benefit from the fixes.

### ISSUE THREAD

**Issue by DesolateIntention** [kappa-maintainer/Sound-Physics#7]
With the mod dead, this fork seems like a solid one to continue on. It would be useful to provide the built jars for everyone.

**Comment by kappa-maintainer** [comment]
Already on CurseForge

**Comment by DesolateIntention** [comment]
> Already on CurseForge

Where?

**Comment by kappa-maintainer** [comment]
https://legacy.curseforge.com/minecraft/mc-mods/sound-physics-remixin

**Comment by DesolateIntention** [comment]
I recommend changing the README, because it says "Downloads are in the releases tab", but that links to the repository you forked. There's nothing indicating how to download your mod.
